import type { ErrorTag } from './types';

/**
 * Typed DEV/OFFLINE FALLBACK seed of the v8 catalog (~2540 target). Spans every
 * grade band so the teacher/exercise-bank/heatmap UIs render real-looking data
 * with no backend running.
 *
 * NOT the source of truth: the live catalog grows continuously on the backend
 * (innova-ai-engine → import-error-catalog → error_tags). Product surfaces show
 * the backend's curated `errorTagName` at runtime and only fall back to
 * `formatHumanName(code)` here when the API omits it. Domain grouping is
 * reconciled across short/long codes via `normalizeDomainCode` (domain-aliases.ts).
 * Curated entries cite Brown & VanLehn (1980) / Resnick-Ford (1981) per error-taxonomy.md.
 */
export const ERROR_TAGS: readonly ErrorTag[] = [
  // ── ARITHMETIC · subtraction ──────────────────────────────────────────────
  {
    code: 'ARITH_SUB_BORROW_OMITTED_TENS_G3',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'SUBTRACTION_NATURAL',
    name_es: 'Reserva omitida en unidades',
    name_en: 'Tens-column borrow omitted',
    description_es: 'Restó la columna de unidades sin pedir prestado a las decenas.',
    detection_pattern: 'student_units == abs(a_units - b_units) when b_units > a_units',
    example_problem: '53 − 26',
    example_canonical: '27',
    example_student_answer: '33',
    applicable_grades: ['G3', 'G4'],
    oa_codes: ['MA03 OA 06', 'MA04 OA 05'],
    prerequisites: ['TRANS_ARITH_FACT_ERROR'],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
    notes: 'Brown & VanLehn 1980, bug #4',
  },
  {
    code: 'ARITH_SUB_BORROW_OMITTED_HUNDREDS_G4',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'SUBTRACTION_NATURAL',
    name_es: 'Reserva omitida en centenas',
    name_en: 'Hundreds-column borrow omitted',
    description_es: 'Igual que la reserva de decenas, pero en la columna de las centenas.',
    example_problem: '423 − 156',
    example_canonical: '267',
    example_student_answer: '337',
    applicable_grades: ['G4', 'G5'],
    oa_codes: ['MA04 OA 05'],
    prerequisites: ['ARITH_SUB_BORROW_OMITTED_TENS_G3'],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ARITH_SUB_MINUEND_SWAPPED_G3',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'SUBTRACTION_NATURAL',
    name_es: 'Restó al revés (menor menos mayor)',
    name_en: 'Subtrahend/minuend swapped per column',
    description_es: 'En una columna restó el dígito menor del mayor para evitar pedir prestado.',
    example_problem: '53 − 26',
    example_canonical: '27',
    example_student_answer: '33',
    applicable_grades: ['G3', 'G4'],
    oa_codes: ['MA03 OA 06'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ARITH_SUB_BORROW_FROM_ZERO_G4',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'SUBTRACTION_NATURAL',
    name_es: 'Pedir prestado al cero incorrecto',
    name_en: 'Borrow-from-zero error',
    description_es: 'Al pedir prestado a una columna con 0 no propaga el préstamo correctamente.',
    example_problem: '100 − 27',
    example_canonical: '73',
    example_student_answer: '83',
    applicable_grades: ['G4'],
    oa_codes: ['MA04 OA 05'],
    prerequisites: ['ARITH_SUB_BORROW_OMITTED_TENS_G3'],
    severity: 'HIGH',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── ARITHMETIC · addition ─────────────────────────────────────────────────
  {
    code: 'ARITH_ADD_CARRY_OMITTED_G3',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'ADDITION_NATURAL',
    name_es: 'Llevada omitida',
    name_en: 'Carry omitted',
    description_es: 'No agregó la llevada a la columna siguiente.',
    example_problem: '38 + 27',
    example_canonical: '65',
    example_student_answer: '55',
    applicable_grades: ['G3'],
    oa_codes: ['MA03 OA 05'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ARITH_ADD_CARRY_WRONG_COLUMN_G3',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'ADDITION_NATURAL',
    name_es: 'Llevada en columna equivocada',
    name_en: 'Carry added to wrong column',
    description_es: 'Agregó la llevada a la misma columna en vez de la siguiente.',
    example_problem: '38 + 27',
    example_canonical: '65',
    example_student_answer: '75',
    applicable_grades: ['G3'],
    oa_codes: ['MA03 OA 05'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── ARITHMETIC · multiplication / division ────────────────────────────────
  {
    code: 'ARITH_MUL_TABLE_RECALL_G4',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'MULTIPLICATION_NATURAL',
    name_es: 'Error de tabla de multiplicar',
    name_en: 'Times-table recall error',
    description_es: 'El procedimiento es correcto pero el hecho de la tabla está mal.',
    example_problem: '7 × 8',
    example_canonical: '56',
    example_student_answer: '54',
    applicable_grades: ['G4', 'G5'],
    oa_codes: ['MA04 OA 04'],
    prerequisites: [],
    severity: 'LOW',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ARITH_MUL_ZERO_TIMES_X_G3',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'MULTIPLICATION_NATURAL',
    name_es: 'Cero por un número distinto de cero',
    name_en: 'Zero times nonzero',
    description_es: 'Multiplicó 0 por un número y obtuvo un resultado distinto de cero.',
    example_problem: '0 × 5',
    example_canonical: '0',
    example_student_answer: '5',
    applicable_grades: ['G3', 'G4'],
    oa_codes: ['MA03 OA 08'],
    prerequisites: [],
    severity: 'LOW',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ARITH_DIV_DIVISOR_DIVIDEND_SWAPPED_G5',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'DIVISION_NATURAL',
    name_es: 'Dividendo y divisor invertidos',
    name_en: 'Divisor/dividend swapped',
    description_es: 'Colocó el divisor dentro y el dividendo afuera de la caja de división.',
    example_problem: '124 ÷ 4',
    example_canonical: '31',
    example_student_answer: '0 r 4',
    applicable_grades: ['G5', 'G6'],
    oa_codes: ['MA05 OA 03'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ARITH_DIV_REMAINDER_GT_DIVISOR_G5',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'DIVISION_NATURAL',
    name_es: 'Resto mayor o igual que el divisor',
    name_en: 'Remainder ≥ divisor',
    description_es: 'Dejó un resto mayor o igual al divisor; aún cabe una vez más.',
    example_problem: '17 ÷ 5',
    example_canonical: '3 r 2',
    example_student_answer: '2 r 7',
    applicable_grades: ['G5', 'G6'],
    oa_codes: ['MA05 OA 03'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── FRACTIONS ─────────────────────────────────────────────────────────────
  {
    code: 'FRACT_ADDSAME_SUM_DENOMINATORS_G5',
    domain_code: 'FRACTIONS',
    subdomain_code: 'FRAC_ADDSUB_SAME',
    name_es: 'Sumó numeradores y denominadores',
    name_en: 'Summed numerators and denominators',
    description_es: 'Con igual denominador sumó también los denominadores.',
    example_problem: '2/5 + 1/5',
    example_canonical: '3/5',
    example_student_answer: '3/10',
    applicable_grades: ['G5'],
    oa_codes: ['MA05 OA 09'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'FRACT_ADDSAME_NOT_REDUCED_G5',
    domain_code: 'FRACTIONS',
    subdomain_code: 'FRAC_SIMPLIFY',
    name_es: 'Resultado no simplificado',
    name_en: 'Result not reduced',
    description_es: 'Resultado correcto pero sin simplificar a su forma mínima.',
    example_problem: '1/4 + 1/4',
    example_canonical: '1/2',
    example_student_answer: '2/4',
    applicable_grades: ['G5', 'G6'],
    oa_codes: ['MA05 OA 09'],
    prerequisites: [],
    severity: 'LOW',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'FRACT_INVERTED_G5',
    domain_code: 'FRACTIONS',
    subdomain_code: 'FRAC_ADDSUB_SAME',
    name_es: 'Fracción invertida',
    name_en: 'Inverted fraction',
    description_es: 'Intercambió numerador y denominador en el resultado.',
    example_problem: '3/5',
    example_canonical: '3/5',
    example_student_answer: '5/3',
    applicable_grades: ['G5'],
    oa_codes: ['MA05 OA 07'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'FRACT_ADDDIFF_COMMON_DENOM_MISSED_G6',
    domain_code: 'FRACTIONS',
    subdomain_code: 'FRAC_ADDSUB_DIFF',
    name_es: 'Sin denominador común',
    name_en: 'Common denominator missed',
    description_es: 'Sumó directo sin buscar un denominador común.',
    example_problem: '1/2 + 1/3',
    example_canonical: '5/6',
    example_student_answer: '2/5',
    applicable_grades: ['G6'],
    oa_codes: ['MA06 OA 04'],
    prerequisites: ['FRACT_ADDSAME_SUM_DENOMINATORS_G5'],
    severity: 'HIGH',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'FRACT_ADDDIFF_WRONG_LCM_G6',
    domain_code: 'FRACTIONS',
    subdomain_code: 'FRAC_ADDSUB_DIFF',
    name_es: 'Mínimo común múltiplo erróneo',
    name_en: 'Wrong LCM',
    description_es: 'El denominador común no es múltiplo de ambos.',
    example_problem: '1/4 + 1/6',
    example_canonical: '5/12',
    example_student_answer: '?/10',
    applicable_grades: ['G6'],
    oa_codes: ['MA06 OA 04'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── INTEGERS ──────────────────────────────────────────────────────────────
  {
    code: 'INT_SIGN_DOUBLE_NEGATIVE_G7',
    domain_code: 'INTEGERS',
    subdomain_code: 'INT_SIGN_RULES',
    name_es: 'Doble negativo mal resuelto',
    name_en: 'Double negative mishandled',
    description_es: 'No aplicó que −(−a) = +a.',
    example_problem: '5 − (−3)',
    example_canonical: '8',
    example_student_answer: '2',
    applicable_grades: ['G7', 'G8'],
    oa_codes: ['MA07 OA 01'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'INT_ADDSUB_SIGN_FLIP_G7',
    domain_code: 'INTEGERS',
    subdomain_code: 'INT_ADD_SUB',
    name_es: 'Signo perdido al operar',
    name_en: 'Sign lost when operating',
    description_es: 'Ignoró el signo del entero al sumar o restar.',
    example_problem: '−7 + 4',
    example_canonical: '−3',
    example_student_answer: '3',
    applicable_grades: ['G7'],
    oa_codes: ['MA07 OA 01'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── DECIMALS ──────────────────────────────────────────────────────────────
  {
    code: 'DEC_ADDSUB_MISALIGNED_POINT_G5',
    domain_code: 'DECIMALS',
    subdomain_code: 'DEC_ADDSUB',
    name_es: 'Coma decimal desalineada',
    name_en: 'Decimal point misaligned',
    description_es: 'No alineó las comas decimales antes de sumar/restar.',
    example_problem: '2.5 + 0.75',
    example_canonical: '3.25',
    example_student_answer: '10.0',
    applicable_grades: ['G5', 'G6'],
    oa_codes: ['MA05 OA 10'],
    prerequisites: ['TRANS_COLUMN_MISALIGNMENT'],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'DEC_MUL_POINT_PLACEMENT_G6',
    domain_code: 'DECIMALS',
    subdomain_code: 'DEC_MUL_DIV',
    name_es: 'Coma mal ubicada al multiplicar',
    name_en: 'Wrong decimal placement (×)',
    description_es: 'No contó la cantidad total de decimales de los factores.',
    example_problem: '0.3 × 0.2',
    example_canonical: '0.06',
    example_student_answer: '0.6',
    applicable_grades: ['G6', 'G7'],
    oa_codes: ['MA06 OA 06'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── PROPORTIONS ───────────────────────────────────────────────────────────
  {
    code: 'PROP_PERCENT_OF_WHOLE_G7',
    domain_code: 'PROPORTIONS',
    subdomain_code: 'PERCENT',
    name_es: 'Porcentaje calculado sobre el total equivocado',
    name_en: 'Percent of wrong base',
    description_es: 'Aplicó el porcentaje a un valor distinto del total de referencia.',
    example_problem: '20% de 150',
    example_canonical: '30',
    example_student_answer: '20',
    applicable_grades: ['G7', 'G8'],
    oa_codes: ['MA07 OA 09'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'PROP_CROSS_MULT_INVERTED_G8',
    domain_code: 'PROPORTIONS',
    subdomain_code: 'PROPORTION',
    name_es: 'Producto cruzado invertido',
    name_en: 'Cross-multiplication inverted',
    description_es: 'Multiplicó en cruz los términos equivocados de la proporción.',
    example_problem: '3/4 = x/8',
    example_canonical: '6',
    example_student_answer: '10.7',
    applicable_grades: ['G8', 'G9'],
    oa_codes: ['MA08 OA 06'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── ALGEBRA LINEAR ────────────────────────────────────────────────────────
  {
    code: 'ALG_LIN_SIGN_FLIP_TRANSPOSE_G8',
    domain_code: 'ALGEBRA_LINEAR',
    subdomain_code: 'EQ_LINEAR',
    name_es: 'No cambió el signo al transponer',
    name_en: 'Sign not flipped on transpose',
    description_es: 'Pasó un término al otro lado sin cambiar su signo.',
    example_problem: 'x + 5 = 12',
    example_canonical: 'x = 7',
    example_student_answer: 'x = 17',
    applicable_grades: ['G8', 'G9'],
    oa_codes: ['MA08 OA 03'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'ALG_LIN_DISTRIBUTE_OMITTED_G8',
    domain_code: 'ALGEBRA_LINEAR',
    subdomain_code: 'EXPR_SIMPLIFY',
    name_es: 'Distributiva incompleta',
    name_en: 'Distribution omitted',
    description_es: 'No distribuyó el factor a todos los términos del paréntesis.',
    example_problem: '2(x + 3)',
    example_canonical: '2x + 6',
    example_student_answer: '2x + 3',
    applicable_grades: ['G8'],
    oa_codes: ['MA08 OA 03'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── ALGEBRA QUADRATIC ─────────────────────────────────────────────────────
  {
    code: 'ALG_QUAD_FORMULA_SIGN_B_G10',
    domain_code: 'ALGEBRA_QUADRATIC',
    subdomain_code: 'QUAD_FORMULA',
    name_es: 'Signo de −b en la fórmula general',
    name_en: 'Wrong sign of −b',
    description_es: 'Usó +b en lugar de −b en la fórmula cuadrática.',
    example_problem: 'x² − 5x + 6 = 0',
    example_canonical: 'x = 2, 3',
    example_student_answer: 'x = −2, −3',
    applicable_grades: ['G10', 'G11'],
    oa_codes: ['MA1M OA 03'],
    prerequisites: ['ALG_LIN_SIGN_FLIP_TRANSPOSE_G8'],
    severity: 'HIGH',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── EXPONENTS / RADICALS ──────────────────────────────────────────────────
  {
    code: 'EXP_LAW_MULTIPLY_EXPONENTS_G8',
    domain_code: 'EXPONENTS_RADICALS',
    subdomain_code: 'EXP_LAWS',
    name_es: 'Multiplicó exponentes al multiplicar bases',
    name_en: 'Multiplied exponents on product',
    description_es: 'Aplicó xᵃ · xᵇ = xᵃᵇ en vez de xᵃ⁺ᵇ.',
    example_problem: 'x² · x³',
    example_canonical: 'x⁵',
    example_student_answer: 'x⁶',
    applicable_grades: ['G8', 'G9'],
    oa_codes: ['MA08 OA 04'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'RADICAL_SUM_UNDER_ROOT_G9',
    domain_code: 'EXPONENTS_RADICALS',
    subdomain_code: 'RADICALS',
    name_es: 'Sumó dentro de la raíz',
    name_en: 'Summed under the root',
    description_es: 'Aplicó √a + √b = √(a+b), que es falso.',
    example_problem: '√9 + √16',
    example_canonical: '7',
    example_student_answer: '5',
    applicable_grades: ['G9', 'G10'],
    oa_codes: ['MA1M OA 02'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── FUNCTIONS ─────────────────────────────────────────────────────────────
  {
    code: 'FUNC_LINEAR_SLOPE_INTERCEPT_SWAP_G9',
    domain_code: 'FUNCTIONS',
    subdomain_code: 'FUNC_LINEAR',
    name_es: 'Pendiente e intercepto intercambiados',
    name_en: 'Slope/intercept swapped',
    description_es: 'En y = mx + n confundió la pendiente con el intercepto.',
    example_problem: 'y = 2x + 3',
    example_canonical: 'm=2, n=3',
    example_student_answer: 'm=3, n=2',
    applicable_grades: ['G9', 'G10'],
    oa_codes: ['MA1M OA 04'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── GEOMETRY ──────────────────────────────────────────────────────────────
  {
    code: 'GEO_AREA_PERIMETER_CONFUSION_G5',
    domain_code: 'GEOMETRY_PLANE',
    subdomain_code: 'GEO_AREA',
    name_es: 'Confundió área con perímetro',
    name_en: 'Area/perimeter confusion',
    description_es: 'Sumó los lados cuando se pedía el área (o viceversa).',
    example_problem: 'Cuadrado lado 4',
    example_canonical: 'Área 16',
    example_student_answer: '16 → puso 16 como perímetro',
    applicable_grades: ['G5', 'G6'],
    oa_codes: ['MA05 OA 20'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'GEO_PYTHAGORAS_LEG_HYP_SWAP_G8',
    domain_code: 'GEOMETRY_PLANE',
    subdomain_code: 'GEO_PYTHAGORAS',
    name_es: 'Cateto e hipotenusa intercambiados',
    name_en: 'Leg/hypotenuse swapped',
    description_es: 'Trató un cateto como hipotenusa al aplicar Pitágoras.',
    example_problem: 'a=3, b=4, c=?',
    example_canonical: 'c = 5',
    example_student_answer: 'c = √7',
    applicable_grades: ['G8', 'G9'],
    oa_codes: ['MA08 OA 09'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── TRIGONOMETRY ──────────────────────────────────────────────────────────
  {
    code: 'TRIG_IDENTITY_PYTHAGOREAN_WRONG_G11',
    domain_code: 'TRIGONOMETRY',
    subdomain_code: 'TRIG_IDENTITY',
    name_es: 'Identidad pitagórica mal aplicada',
    name_en: 'Pythagorean identity misapplied',
    description_es: 'Usó sin²θ + cos²θ con un valor distinto de 1.',
    example_problem: 'sin²θ + cos²θ',
    example_canonical: '1',
    example_student_answer: '2',
    applicable_grades: ['G11', 'G12'],
    oa_codes: ['MA3M OA 03'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── LOGARITHMS ────────────────────────────────────────────────────────────
  {
    code: 'LOG_PRODUCT_TO_SUM_INV_G11',
    domain_code: 'LOGARITHMS',
    subdomain_code: 'LOG_PROPERTIES',
    name_es: 'Producto a suma invertido',
    name_en: 'Product-to-sum inverted',
    description_es: 'Aplicó log(ab) = log a · log b en vez de log a + log b.',
    example_problem: 'log(2·5)',
    example_canonical: 'log2 + log5',
    example_student_answer: 'log2 · log5',
    applicable_grades: ['G11', 'G12'],
    oa_codes: ['MA3M OA 02'],
    prerequisites: [],
    severity: 'HIGH',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── SEQUENCES / STATISTICS ────────────────────────────────────────────────
  {
    code: 'SEQ_ARITH_COMMON_DIFF_SIGN_G7',
    domain_code: 'SEQUENCES',
    subdomain_code: 'SEQ_ARITHMETIC',
    name_es: 'Signo de la diferencia común',
    name_en: 'Common-difference sign error',
    description_es: 'En una progresión decreciente tomó la diferencia como positiva.',
    example_problem: '10, 7, 4, …',
    example_canonical: 'd = −3',
    example_student_answer: 'd = 3',
    applicable_grades: ['G7', 'G8'],
    oa_codes: ['MA07 OA 05'],
    prerequisites: [],
    severity: 'LOW',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'STAT_MEAN_FORGOT_DIVIDE_G6',
    domain_code: 'STATISTICS',
    subdomain_code: 'STAT_CENTER',
    name_es: 'Promedio sin dividir',
    name_en: 'Mean without dividing',
    description_es: 'Sumó los datos pero no dividió por la cantidad de datos.',
    example_problem: 'media de 4, 6, 8',
    example_canonical: '6',
    example_student_answer: '18',
    applicable_grades: ['G6', 'G7'],
    oa_codes: ['MA06 OA 13'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'LLM_GENERATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── TRANSVERSAL (cross-domain) ────────────────────────────────────────────
  {
    code: 'TRANS_COLUMN_MISALIGNMENT',
    domain_code: 'TRANSVERSAL',
    subdomain_code: 'MISALIGNMENT',
    name_es: 'Columnas desalineadas',
    name_en: 'Column misalignment',
    description_es: 'Alineó mal las columnas (unidades con decenas, etc.).',
    example_problem: '53 + 6',
    example_canonical: '59',
    example_student_answer: '113',
    applicable_grades: ['G2', 'G3', 'G4', 'G5'],
    oa_codes: [],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  {
    code: 'TRANS_ARITH_FACT_ERROR',
    domain_code: 'TRANSVERSAL',
    subdomain_code: 'ARITH_FACT',
    name_es: 'Error en hecho aritmético básico',
    name_en: 'Basic arithmetic fact error',
    description_es: 'Procedimiento correcto, pero falla un hecho básico (7−3, 6+5…).',
    example_problem: '7 − 3',
    example_canonical: '4',
    example_student_answer: '5',
    applicable_grades: ['G1', 'G2', 'G3', 'G4', 'G5', 'G6'],
    oa_codes: [],
    prerequisites: [],
    severity: 'LOW',
    source: 'CURATED',
    status: 'ACTIVE',
    created_at: '2026-05-18',
  },
  // ── DRAFT / DEPRECATED — to exercise the admin error-catalog UI ────────────
  {
    code: 'FRACT_ADDSAME_NUMERATOR_ALSO_DENOM_G5',
    domain_code: 'FRACTIONS',
    subdomain_code: 'FRAC_ADDSUB_SAME',
    name_es: '(field-reported) Numerador copiado al denominador',
    name_en: 'Numerator copied to denominator',
    description_es:
      'Sugerencia de profe en terreno: copia el numerador final también como denominador.',
    example_problem: '2/5 + 2/5',
    example_canonical: '4/5',
    example_student_answer: '4/4',
    applicable_grades: ['G5'],
    oa_codes: ['MA05 OA 09'],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'FIELD_REPORTED',
    status: 'DRAFT',
    created_at: '2026-06-05',
    notes: 'Reportado por profe piloto · pendiente revisión pedagógica.',
  },
  {
    code: 'ARITH_SUB_BORROW_TENS_LEGACY',
    domain_code: 'ARITHMETIC',
    subdomain_code: 'SUBTRACTION_NATURAL',
    name_es: '(obsoleto) Reserva de decenas — código viejo',
    name_en: 'Legacy tens borrow',
    description_es: 'Código plano v7 reemplazado por la versión jerárquica con grade hint.',
    example_problem: '53 − 26',
    example_canonical: '27',
    example_student_answer: '33',
    applicable_grades: ['G3'],
    oa_codes: [],
    prerequisites: [],
    severity: 'MEDIUM',
    source: 'CURATED',
    status: 'DEPRECATED',
    created_at: '2026-04-29',
    deprecated_by: 'ARITH_SUB_BORROW_OMITTED_TENS_G3',
  },
] as const;
