#!/usr/bin/env node
// codegen:error-tags — emits a stable compile-time enum of error-tag codes
// (v8 §6.2 ErrorTagId). Source of truth is the backend ErrorTag table; until the
// OpenAPI/DB codegen is wired, it reads the local seed so the command is real.
//
//   pnpm run codegen:error-tags   →  src/error-tags.generated.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const seedPath = join(here, '..', 'src', 'seed.ts');
const outPath = join(here, '..', 'src', 'error-tags.generated.ts');

const seed = readFileSync(seedPath, 'utf8');
const codes = [...seed.matchAll(/code:\s*'([A-Z0-9_]+)'/g)].map((m) => m[1]);
const unique = [...new Set([...codes, 'CORRECT', 'UNCLASSIFIED', 'IRRELEVANT_INPUT', 'EMPTY_RESPONSE'])];

const body = unique.map((c) => `  ${c}: '${c}',`).join('\n');
const out = `// AUTO-GENERATED by scripts/codegen.mjs — do not edit.
// Replace the seed source with the backend ErrorTag table when codegen is wired.
export const ErrorTagId = {
${body}
} as const;
export type ErrorTagIdValue = (typeof ErrorTagId)[keyof typeof ErrorTagId];
`;

writeFileSync(outPath, out);
console.log(`codegen:error-tags → ${unique.length} codes → ${outPath}`);
